# Generated by Django 5.0.6 on 2024-06-10 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson1', '0004_course_alter_product_category_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_text', models.CharField(max_length=100)),
                ('long_text', models.TextField()),
                ('number', models.IntegerField()),
                ('float_number', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('true_false', models.BooleanField(default=False)),
                ('many_to_many', models.ManyToManyField(related_name='onetomany', to='lesson1.course')),
                ('related', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='one_to_many', to='lesson1.course')),
            ],
        ),
    ]
